// <auto-generated />
using System;
using BoardBard.Core.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BoardBard.Core.Migrations.Slite
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20250221235859_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("BoardBard.Core.Models.App.LabelType", b =>
                {
                    b.Property<int>("LabelTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LabelTypeId");

                    b.ToTable("LabelTypes", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskActivity", b =>
                {
                    b.Property<int>("TaskActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskActivityId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskActivities", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskBoard", b =>
                {
                    b.Property<int>("TaskBoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Starred")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskBoardId");

                    b.ToTable("TaskBoards", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskCard", b =>
                {
                    b.Property<int>("TaskCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Collapsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskBoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskCardId");

                    b.HasIndex("TaskBoardId");

                    b.ToTable("TaskCards", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskCardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskCardId");

                    b.ToTable("Tasks", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskLabelLink", b =>
                {
                    b.Property<int>("TaskLabelLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskLabelLinkId");

                    b.HasIndex("LabelTypeId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskLabelLinks", "Core");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskActivity", b =>
                {
                    b.HasOne("BoardBard.Core.Models.App.TaskItem", "TaskItem")
                        .WithMany("Activities")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskCard", b =>
                {
                    b.HasOne("BoardBard.Core.Models.App.TaskBoard", "TaskBoard")
                        .WithMany("TaskCards")
                        .HasForeignKey("TaskBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBoard");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskItem", b =>
                {
                    b.HasOne("BoardBard.Core.Models.App.TaskCard", "TaskCard")
                        .WithMany("TaskItems")
                        .HasForeignKey("TaskCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskCard");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskLabelLink", b =>
                {
                    b.HasOne("BoardBard.Core.Models.App.LabelType", "LabelType")
                        .WithMany()
                        .HasForeignKey("LabelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardBard.Core.Models.App.TaskItem", "TaskItem")
                        .WithMany("LabelLinks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabelType");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskBoard", b =>
                {
                    b.Navigation("TaskCards");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskCard", b =>
                {
                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("BoardBard.Core.Models.App.TaskItem", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("LabelLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
